spring:
  data:
    mongodb:
      database: instaclone_auth

server:
  port: 8081
#  ssl:
#    enabled: true
#    key-store: sss
security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic